# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cartoWorks
                                 A QGIS plugin
 to add gis data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-22
        copyright            : (C) 2020 by SiteRecon
        email                : info@siterecon.ai
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load cartoWorks class from file cartoWorks.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .carto_works import cartoWorks
    return cartoWorks(iface)
