# -*- coding: utf-8 -*-
"""
/***************************************************************************
 cartoWorks
                                 A QGIS plugin
 to add gis data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-22
        git sha              : $Format:%H$
        copyright            : (C) 2020 by SiteRecon
        email                : info@siterecon.ai
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
from qgis.core import QgsProject, Qgis
from PyQt5 import QtCore, QtGui, QtWidgets
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .carto_works_dialog import cartoWorksDialog
import os.path, glob
from .add_data_dialog import Ui_addDataDialogBase
from qgis.PyQt.QtWidgets import QAction, QFileDialog
import requests
import json

class cartoWorks:

    """QGIS Plugin Implementation."""
    sessionToken=""
    def __init__(self, iface):

        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'cartoWorks_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Cartoworks')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('cartoWorks', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/carto_works/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Cartoworks'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True

    def _addDataDialog(self):
        self.window=QtWidgets.QDialog()
        self.ui=Ui_addDataDialogBase()
        self.ui.setupUi(self.window)
        self.window.show()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Cartoworks'),
                action)
            self.iface.removeToolBarIcon(action)


    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False

        if self.sessionToken:
            self._addDataDialog()
            return True
        else:
            self.dlg = cartoWorksDialog()

        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Do something useful here - delete the line containing pass and
            # substitute with your code.
            username = self.dlg.username_field.text()
            password = self.dlg.password_field.text()


            url ="http://18.225.10.202:8000/api/user/login/"
            data={
                "email" :""+username+"",
                "password": ""+password+""
            }

            r = requests.post(url, data=data)
            response_value=r.text
            status_value=r.status_code
            print("status value",status_value)
            print("response value",response_value)

            data = json.loads(response_value)
            gettoken=data.get('token')
            print("get value",data.get('token'))



#            url = "https://reqres.in/api/login"

#            payload = {"email":""+username+"","password":""+password+""}

#            payload = "{\n    \"email\": \""+username+"\",\n    \"password\": \""+password+"\"\n}"
#            headers = {
#                'content-type': "application/json",
#                'cache-control': "no-cache",
#                'postman-token': "5882dfa1-dc13-68f5-1970-5e6bf22594ad"
#                }

#            response = requests.request("POST", url, data=payload, headers=headers, params=querystring)
#            response = requests.request("POST", url, data=payload, headers=headers)
#            status_value=response.status_code
#            response_value=response.text

            if(status_value==200  and gettoken is not None):
                print("data value",data["token"])
                self.sessionToken=data["token"]
                self._addDataDialog()


                self.iface.messageBar().pushMessage(
                  "Success", "Loggedin sucessfully ",
                  level=Qgis.Success, duration=3)

#                  Second dialogbox functionality code starts

#                  Second dialogbox functionality code ends
            else:
                self.iface.messageBar().pushMessage(
                  "Error", "Invalid details",
                  level=Qgis.Critical, duration=3)
